### ISSUE TITLE
Environment problem

### ISSUE THREAD

**Issue by reverdya** [cusicand/lidarhd_ign_downloader#1]
Thanks for the amazing tool. It saved me a lot of time to not have to code it myself.
I'm not very familiar with environments, but it was not as straightforward to install for me as described.
After fiddling around for a while, this is what I had to do to make it work:

git clone https://github.com/cusicand/lidarhd_ign_downloader.git
     cd ./lidarhd_ign_downloader
(The changes to the bashrc)
     source ~/.bashrc
     conda env create -f py39.yml
     source activate py39
     pip install wget
     pip install tdqm
     python lidar_downloader.py aoi_double.shp -tr 1
     conda deactivate

From what I gathered online the fact of having to use 'source activate' instead of 'conda activate' could have something to do with an older version of conda.
Regarding the necessity to install wget and tdqm inside the environment, that's something I cannot get my head around. Because:
     conda env create -f py39.yml
     source activate py39
     conda list
shows both library as being already installed, before the pip commands. But running the python script will return 'ModuleNotFoundError'

I don't think it requires a modification to you code, it seems very conda installation dependant, but I wanted to leave my workaround here if either someone needed it.
Thank you again
Best
Alix

**Comment by cusicand** [comment]
Hi Alix,
Thanks for your comment.

Yes, I agree with you that this script is python-conda dependent. However, this is the way I found to work with python and lead with library dependencies.
I have updated the instructions in the `Readme.md` file to be more explicit with all the steps.

Please don't hesitate to contact me again if you still have problems with the installation.
Best
Diego

**Comment by reverdya** [comment]
Hi,
Thanks it looks even clearer now in the Readme.
For me it worked like a charm after doing the adjustments I wrote above and I downloaded quite an extensive domain near the Lautaret pass (3.5Gb tiff) with no trouble.
Thanks again for the work
Best
Alix

**Comment by cusicand** [comment]
Welcome!!
Please use the DOI code to cite this tool properly.

Best
Diego
