### ISSUE TITLE
IGN URL broken

### ISSUE THREAD

**Issue by sgascoin** [cusicand/lidarhd_ign_downloader#6]
I think that IGN has closed their server https://diffusion-lidarhd-classe.ign.fr/download/lidar/shp/classe

**Comment by cusicand** [comment]
Dear Simon,

I am seeing the same problem.
My first guess is that IGN regularly updates the database (shapefile) and temporarily blocks access.  In my case it works fine after a few days.
I cannot put the database on Github. I am trying to figure out where to put it without conflicting with IGN.

Sorry for the bug
Best
Diego

**Comment by cusicand** [comment]
Dear @sgascoin,

I have been monitoring access to the IGN database and it is still closed. In this regard, I made a copy in [Zenodo](https://zenodo.org/records/13793544) to ensure the continuity and use of this tool. In [version 3.0](https://github.com/cusicand/lidarhd_ign_downloader/releases/tag/v3.0) of this tool I continue to demand access to the IGN database. If it is not found, It will search in the alternative link.

In this database we have all the French Alps and Pyrenees already treated. Please do not hesitate to make a copy of version 3.0.

In case of any error/bug, don't hesitate to let me know.

Regards
Diego
