### ISSUE TITLE
the input feature must have a "aoi_name" column ..

### ISSUE THREAD

**Issue by sgascoin** [cusicand/lidarhd_ign_downloader#7]
.. otherwise it crashes

https://github.com/cusicand/lidarhd_ign_downloader/blob/18aa6976fa9b1a0cc1346904af3198b93be06cfe/lidar_downloader.py#L361

**Comment by sgascoin** [comment]
I did not notice that it was specified in the doc.

**Comment by Ravisik** [comment]
If you don't want to bother with aoi_name, you can add it automatically using the shapefile name 

```
aoi_df = gpd.read_file(args.aoi_file, engine="pyogrio")
aoi_df["aoi_name"] = args.aoi_file.split('/')[-1]  # adding this to automatically create aoi name...
```
