### ISSUE TITLE
The input geometry must be in Lambert 93 ..

### ISSUE THREAD

**Issue by sgascoin** [cusicand/lidarhd_ign_downloader#8]
.. otherwise the intersection with the tiling grid fails

**Comment by Ravisik** [comment]
Hi Simon, 

A simple trick can be used to automatically reproject the geodataframe in Lambert93. In the main file you can add this line after the following command: 

```
aoi_df = gpd.read_file(args.aoi_file, engine="pyogrio")
aoi_df = aoi_df.to_crs(epsg=2154)
```

Florian M

**Comment by sgascoin** [comment]
Yes, maybe add this to a pull request? Not sure why Diego closed the issue?
